batch_size: 1
num_workers: 6
infer_overlap: 0.6
learning_rate: 0.0001
max_epochs: 300
sw_batch_size: 2
val_every: 1
weight_decay: 0.00001
solver_name: Adam
loss_type: dice
pretrained: False
resume: False
seed: 123
colab: False
irl: True
sines: False
my_pc: False
new_max_epochs: None
project_name: "Visionary Neuro GLI"
exp_name: "SegResNet_Run_Without_Data_Aug_v1.1.1"
wand_api_key: 981af7fdfb60c59545a06fcba96db2a57079cdf9